### PR TITLE
Switch to clap v3

### PR DESCRIPTION
**Pull request by msfjarvis**
Incrementally upgrades to clap v3 in-place, splits our code across separate files, then migrates to the macro-backed type-safe config

### CODE REVIEW

**Comment by SphericalKat** [comment]
No colored output?

**Comment by msfjarvis** [comment]
> No colored output?

Not sure what's up with that, the [default features](https://github.com/clap-rs/clap/blob/v3.0.0-beta.2/Cargo.toml#L90) include `color`.

**Comment by msfjarvis** [comment]
Well, [okay then](https://github.com/clap-rs/clap/commit/d985755ca1ea4be989b2a335ab123d5025904cc5).

**Comment by msfjarvis** [comment]
Might also wanna add shell completion at some point: https://github.com/clap-rs/clap/blob/master/clap_derive/examples/value_hints_derive.rs

**Review by SphericalKat — APPROVED** [review]
LGTM imo

**Pull request merged**
